### ISSUE TITLE
POST simple data 

### ISSUE THREAD

**Issue by Wyzix33** [chrisdavies/alite#3]
Hi, i didn't get a change to thank you for your help and responses :+1:  and here i am with another question, is it possible to post simple data say a=1 without creating a FormData() or sending json array?
For now i do this:

```
var data = new FormData();
data.append('a','1');
alite({
     url: url,
     method: 'post',
     data: data,
     raw: true
});
```

and if i try to send 
data = "a=1";
I get a post request without name and value "a=1"
Thanks

**Comment by chrisdavies** [comment]
Yup. You have a number of options, depending on what your back-end system supports. You can send data via query string in the URL, or in the body of your request as any format your back-end supports ( JSON, XML, form data, etc.)

I'd recommend sticking with JSON unless there's a good reason not to. It makes your API easier to consume from a diverse range of situations. Serializing your own data (e.g. building an "a=1" string) is generally a bad idea, because you need to reinvent escaping. (What if your users typed '=' as their input or '&'?).

So in general, I send data as a JSON object (not as a JSON array).

**Comment by Wyzix33** [comment]
I agree, but I am updating an old web app, and some modules are on a remote server that needs to work with normal post for some data retrieval, it should be a simple get, but it is a post... and i was thinking i can do that post without building a new FormData(), but it's no big deal, i can leave it like this :)
Thanks for your input, i will try to convince them to change their back-end. For my app, JSON are generated with your form-to-obj :+1:

**Comment by chrisdavies** [comment]
Ha ha ha. Good to hear about form-to-obj. Well, given what you're describing, if your app has jQuery, you can use their form serialization. Otherwise, you're probably doing the best thing.
